// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzvpedwywvkjvgivmhpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56dnBlZHd5d3ZranZnaXZtaHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjIxMTgsImV4cCI6MjA2NTYzODExOH0.0pqSW803DtEOJccfoXzGrrLn5smXhnd7NEFkjJBdNiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);